apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::358871393576:role/prod-eks-node-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::358871393576:role/prod-eks-node-role\n  groups:\n  - system:bootstrappers\n  - system:nodes\n  username: system:node:{{EC2PrivateDNSName}}\n\n- rolearn: arn:aws:iam::358871393576:role/github-actions-terraform-role\n  groups:\n  - system:masters\n  username: github-actions\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2026-01-26T03:22:44Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"733","uid":"8a736ff3-d1aa-4f5c-beaa-878e18a1909c"}}
  creationTimestamp: "2026-01-26T03:22:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "10107"
  uid: 8a736ff3-d1aa-4f5c-beaa-878e18a1909c
